### ISSUE TITLE
Remove width requirement

### ISSUE THREAD

**Issue by skch-17** [NikolaiMe/textbox-for-pdfkit#2]
If you change the following lines, the user is able to opt out the width and use own linebreaks.

textMeasurment.js line: 23
` return paragraphWidth <= textWidth || textWidth === undefined;`

lineWrapper.js line: 23
`if (textpart.width <= spaceLeftInLine || textWidth === undefined) {`

**Comment by NikolaiMe** [comment]
Hi @skch-17,

did I get you right that you'd like to turn off the automatic line-wrapping? So that new-lines are just created by \n or 'newline' attribute?

Could you explain it a little more? What's the intention behind it? The issue with this request is, that the whole package is depending on the width of the text-field. E.g. if you like to have centered text: Where to center it, if there is no known width. 

If you are just using left-aligned text for your project you can just use very big textbox-widths as a workaround.

**Comment by skch-17** [comment]
First of all, yes I am currently using left aligned text only. The workaround with a huge textbox-width works as expected.

I see that right aligend and centered text require a fixed width to callculate otherwise one would have to take the longest line as width reference. (Just came to my mind)

To calrify my initial intend: When you use left aligned text and you want the line breaks to be forced  ("\n" ) then you have to use the workaround with the huge width, which is in my eyes unexpected. I think just **adding a sentence to the nice docs would be enough though**.
